export const cardReplacements = [
  //Energy
  { from: 'Basic {D} Energy Energy 15', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy Energy 24', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy Energy 33', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy Energy 42', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy Energy 51', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy EVO 97', to: 'Darkness Energy EVO 97' },
  { from: 'Basic {D} Energy BLW 111', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy GEN 81', to: 'Darkness Energy 7' },
  { from: 'Basic {D} Energy XY 138', to: 'Darkness Energy 7' },

  { from: 'Grass Energy SVE 1', to: 'Grass Energy 1' },
  { from: 'Fire Energy SVE 2', to: 'Fire Energy 2' },
  { from: 'Water Energy SVE 3', to: 'Water Energy 3' },
  { from: 'Lightning Energy SVE 4', to: 'Lightning Energy 4' },
  { from: 'Psychic Energy SVE 5', to: 'Psychic Energy 5' },
  { from: 'Fighting Energy SVE 6', to: 'Fighting Energy 6' },
  { from: 'Darkness Energy SVE 7', to: 'Darkness Energy 7' },
  { from: 'Metal Energy SVE 8', to: 'Metal Energy 8' },

  //BS
  { from: 'Pokemon Breeder BS 76', to: 'Pokémon Breeder BS 76' },
  { from: 'Pokemon Trader BS 77', to: 'Pokémon Trader BS 77' },

  //FO
  { from: 'Recycle FO 61', to: 'Gambler FO 61' },

  //BWP
  { from: 'Tropical Beach BWP 50', to: 'Tropical Beach BWP50 BWP 50' },

  //BLW
  { from: 'Zoroark BLW 71', to: 'Zoroark BW 71' },

  //ROS
  { from: 'Double Dragon Energy ROS 97', to: 'Double Dragon Energy SUM 97' },

  //BKP
  { from: 'Delinquent BKP 98', to: 'Delinquent BKT 98' },

  //GRI
  { from: 'Mallow GRI 127', to: 'Mallow TEF 127' },

  //SHF
  { from: 'SnomSV SHF SV33', to: 'Applin SHF SV33' },

  //DRM
  { from: 'Feebas DRM 28', to: 'Feebas BCR 28' },

  //SLG
  { from: 'Warp Energy SLG 70', to: 'Warp Energy SHL 70' },

  //UPR
  { from: 'Mt. Coronet UPR 130', to: 'Mt. Coronet RCL 130' },

  //UNB
  { from: 'Porygon-Z UNB 157', to: 'Porygon-Z PAL 157' },

  //RCL
  { from: 'Horror Psychic Energy RCL 172', to: 'Horror Psychic Energy DAA 172' },

  //CRE
  { from: 'Klara CRE 145', to: 'Klara CRE 145 145' },

  //PGO
  { from: 'PokéStop PGO 68', to: 'PokeStop PGO 68' },

  //ASR
  { from: 'Hisuian Qwilfish ASR 89', to: 'Hisuian Qwilfish2 ASR 89' },

  //CRZ
  { from: 'Zacian VSTAR CRZ 96', to: 'Zacian VSTAR 96' },

  //SVI
  { from: 'Pokégear 3.0 SVI 186', to: 'Pokegear SVI 186' },
  { from: 'Pokémon Catcher SVI 187', to: 'Pokemon Catcher SVI 187' },
  { from: 'Professor\'s Research SVI 189', to: 'Professor\'s Research SVI 189' },
  { from: 'Professor\'s Research SVI 190', to: 'Professor\'s Research SVI 190' },
  { from: 'Riolu SVI 113', to: 'Riolu2 SVI 113' },

  //SVI FA
  { from: 'Armarouge SVI 203', to: 'ArmarougeIR SVI 203' },
  { from: 'Arven SVI 235', to: 'ArvenFA SVI 235' },
  { from: 'Arven SVI 249', to: 'ArvenSIR SVI 249' },
  { from: 'Fighting Energy SVI 258', to: 'Fighting EnergyHR SVI 258' },
  { from: 'Lightning Energy SVI 257', to: 'Lightning EnergyHR SVI 257' },
  { from: 'Gardevoir ex SVI 228', to: 'Gardevoir exFA SVI 228' },
  { from: 'Gardevoir ex SVI 245', to: 'Gardevoir exSIR SVI 245' },
  { from: 'Jacq SVI 236', to: 'JacqFA SVI 236' },
  { from: 'Jacq SVI 250', to: 'JacqSIR SVI 250' },
  { from: 'Katy SVI 237', to: 'KatyFA SVI 237' },
  { from: 'Koraidon ex SVI 231', to: 'Koraidon exFA SVI 231' },
  { from: 'Koraidon ex SVI 247', to: 'Koraidon exSIR SVI 247' },
  { from: 'Koraidon ex SVI 254', to: 'Koraidon exHR SVI 254' },
  { from: 'Magnezone ex SVI 226', to: 'Magnezone exFA SVI 226' },
  { from: 'Miraidon ex SVI 227', to: 'Miraidon exFA SVI 227' },
  { from: 'Miraidon ex SVI 244', to: 'Miraidon exSIR SVI 244' },
  { from: 'Miraidon ex SVI 253', to: 'Miraidon exHR SVI 253' },
  { from: 'Miriam SVI 238', to: 'MiriamFA SVI 238' },
  { from: 'Miriam SVI 251', to: 'MiriamSIR SVI 251' },
  { from: 'Nest Ball SVI 255', to: 'Nest BallHR SVI 255' },
  { from: 'Penny SVI 239', to: 'PennyFA SVI 239' },
  { from: 'Penny SVI 252', to: 'PennySIR SVI 252' },
  { from: "Professor's Research SVI 242", to: "Professor's ResearchFA1 SVI 242" },
  { from: "Professor's Research SVI 241", to: "Professor's ResearchFA2 SVI 241" },
  { from: 'Ralts SVI 211', to: 'RaltsIR SVI 211' },
  { from: 'Rare Candy SVI 256', to: 'Rare CandyHR SVI 256' },
  { from: 'Skwovet SVI 222', to: 'SkwovetIR SVI 222' },
  { from: 'Team Star Grunt SVI 242', to: 'Team Star GruntFA SVI 242' },

  //PAL
  { from: 'Frigibax PAL 57', to: 'Frigibax PAL1 57' },
  { from: 'Frigibax PAL 58', to: 'Frigibax PAL2 58' },
  //PAL FA
  { from: 'Frigibax PAL 208', to: 'FrigibaxIR PAL 208' },
  { from: 'Arctibax PAL 209', to: 'ArctibaxIR PAL 209' },
  { from: 'Baxcalibur PAL 210', to: 'BaxcaliburIR PAL 210' },
  { from: 'Flamigo PAL 227', to: 'FlamigoIR PAL 227' },
  { from: 'Meowscarada ex PAL 231', to: 'Meowscarada exFA PAL 231' },
  { from: 'Wo-Chien ex PAL 232', to: 'Wo-Chien exFA PAL 232' },
  { from: 'Chi-Yu ex PAL 234', to: 'Chi-Yu exFA PAL 234' },
  { from: 'Chien-Pao ex PAL 236', to: 'Chien-Pao exFA PAL 236' },
  { from: 'Ting-Lu ex PAL 243', to: 'Ting-Lu exFA PAL 243' },
  { from: 'Noivern ex PAL 246', to: 'Noivern exFA PAL 246' },
  { from: 'Squawkabilly ex PAL 247', to: 'Squawkabilly exFA PAL 247' },
  { from: 'Boss\'s Orders PAL 248', to: 'Boss\'s OrdersFA PAL 248' },
  { from: 'Clavell PAL 249', to: 'ClavellFA PAL 249' },
  { from: 'Giacomo PAL 252', to: 'GiacomoFA PAL 252' },
  { from: 'Grusha PAL 253', to: 'GrushaFA PAL 253' },
  { from: 'Iono PAL 254', to: 'IonoFA PAL 254' },
  { from: 'Meowscarada ex PAL 256', to: 'Meowscarada exSIR PAL 256' },
  { from: 'Wo-Chien ex PAL 257', to: 'Wo-Chien exSIR PAL 257' },
  { from: 'Chi-Yu ex PAL 259', to: 'Chi-Yu exSIR PAL 259' },
  { from: 'Chien-Pao ex PAL 261', to: 'Chien-Pao exSIR PAL 261' },
  { from: 'Ting-Lu ex PAL 263', to: 'Ting-Lu exSIR PAL 263' },
  { from: 'Squawkabilly ex PAL 264', to: 'Squawkabilly exSIR PAL 264' },
  { from: 'Boss\'s Orders PAL 265', to: 'Boss\'s OrdersSIR PAL 265' },
  { from: 'Giacomo PAL 267', to: 'GiacomoSIR PAL 267' },
  { from: 'Grusha PAL 268', to: 'GrushaSIR PAL 268' },
  { from: 'Iono PAL 269', to: 'IonoSIR PAL 269' },
  { from: 'Meowscarada ex PAL 271', to: 'Meowscarada exHR PAL 271' },
  { from: 'Chien-Pao ex PAL 274', to: 'Chien-Pao exHR PAL 274' },
  { from: 'Ting-Lu ex PAL 275', to: 'Ting-Lu exHR PAL 275' },
  { from: 'Super Rod PAL 276', to: 'Super RodHR PAL 276' },
  { from: 'Superior Energy Retrieval PAL 277', to: 'Superior Energy RetrievalHR PAL 277' },
  { from: 'Froslass ex PAR 217', to: 'FroslassexFA PAR 217' },
  { from: 'Garchomp ex PAR 219', to: 'GarchompexFA PAR 219' },
  { from: 'Tsareena ex PAR 220', to: 'TsareenaexFA PAR 220' },
  { from: 'Tapu Koko ex PAR 222', to: 'TapuKokoexFA PAR 222' },
  { from: 'Iron Hands ex PAR 223', to: 'IronHandsexFA PAR 223' },
  { from: 'Iron Valiant ex PAR 225', to: 'IronValiantexFA PAR 225' },
  { from: 'Hoopa ex PAR 226', to: 'HoopaexFA PAR 226' },
  { from: 'Sandy Shocks ex PAR 228', to: 'SandyShocksexFA PAR 228' },
  { from: 'Roaring Moon ex PAR 229', to: 'RoaringMoonexFA PAR 229' },
  { from: 'Gholdengo ex PAR 231', to: 'GholdengoexFA PAR 231' },
  { from: 'Bombirdier ex PAR 234', to: 'BombirdierexFA PAR 234' },
  { from: 'Mela PAR 236', to: 'MelaFA PAR 236' },
  { from: 'Professor Sada\'s Vitality PAR 239', to: 'ProfessorSadasVitalityFA PAR 239' },
  { from: 'Professor Turo\'s Scenario PAR 240', to: 'ProfessorTurosScenarioFA PAR 240' },
  { from: 'Tulip PAR 244', to: 'TulipFA PAR 244' },
  { from: 'Garchomp ex PAR 245', to: 'GarchompexSIR PAR 245' },
  { from: 'Tapu Koko ex PAR 247', to: 'TapuKokoexSIR PAR 247' },
  { from: 'Iron Hands ex PAR 248', to: 'IronHandsexSIR PAR 248' },
  { from: 'Iron Valiant ex PAR 249', to: 'IronValiantexSIR PAR 249' },
  { from: 'Sandy Shocks ex PAR 250', to: 'SandyShocksexSIR PAR 250' },
  { from: 'Roaring Moon ex PAR 251', to: 'RoaringMoonexSIR PAR 251' },
  { from: 'Gholdengo ex PAR 252', to: 'GholdengoexSIR PAR 252' },
  { from: 'Mela PAR 254', to: 'MelaSIR PAR 254' },
  { from: 'Professor Sada\'s Vitality PAR 256', to: 'ProfessorSadasVitalitySIR PAR 256' },
  { from: 'Professor Turo\'s Scenario PAR 257', to: 'ProfessorTurosScenarioSIR PAR 257' },
  { from: 'Tulip PAR 259', to: 'TulipSIR PAR 259' },
  { from: 'Garchomp ex PAR 260', to: 'GarchompexHR PAR 260' },
  { from: 'Iron Valiant ex PAR 261', to: 'IronValiantexHR PAR 261' },
  { from: 'Roaring Moon ex PAR 262', to: 'RoaringMoonexHR PAR 262' },
  { from: 'Beach Court PAR 263', to: 'BeachCourtHR PAR 263' },
  { from: 'Counter Catcher PAR 264', to: 'CounterCatcherHR PAR 264' },
  { from: 'Luxurious Cape PAR 265', to: 'LuxuriousCapeHR PAR 265' },
  { from: 'Reversal Energy PAR 266', to: 'ReversalEnergyHR PAR 266' },

  //151
  //151 FA
  { from: 'Bulbasaur MEW 166', to: 'BulbasaurIR MEW 166' },
  { from: 'Ivysaur MEW 167', to: 'IvysaurIR MEW 167' },
  { from: 'Charmander MEW 168', to: 'CharmanderIR MEW 168' },
  { from: 'Charmeleon MEW 169', to: 'CharmeleonIR MEW 169' },
  { from: 'Squirtle MEW 170', to: 'SquirtleIR MEW 170' },
  { from: 'Wartortle MEW 171', to: 'WartortleIR MEW 171' },
  { from: 'Nidoking MEW 174', to: 'NidokingIR MEW 174' },
  { from: 'Venusaur ex MEW 182', to: 'Venusaur exFA MEW 182' },
  { from: 'Charizard ex MEW 183', to: 'Charizard exFA MEW 183' },
  { from: 'Blastoise ex MEW 184', to: 'Blastoise exFA MEW 184' },
  { from: 'Arbok ex MEW 185', to: 'Arbok exFA MEW 185' },
  { from: 'Alakazam ex MEW 188', to: 'Alakazam exFA MEW 188' },
  { from: 'Kangaskhan ex MEW 190', to: 'Kangaskhan exFA MEW 190' },
  { from: 'Zapdos ex MEW 192', to: 'Zapdos exFA MEW 192' },
  { from: 'Mew ex MEW 193', to: 'Mew exFA MEW 193' },
  { from: 'Erika\'s Invitation MEW 196', to: 'Erika\'s InvitationFA MEW 196' },
  { from: 'Giovanni\'s Charisma MEW 197', to: 'Giovanni\'s CharismaFA MEW 197' },
  { from: 'Venusaur ex MEW 198', to: 'Venusaur exSIR MEW 198' },
  { from: 'Charizard ex MEW 199', to: 'Charizard exSIR MEW 199' },
  { from: 'Blastoise ex MEW 200', to: 'Blastoise exSIR MEW 200' },
  { from: 'Alakazam ex MEW 201', to: 'Alakazam exSIR MEW 201' },
  { from: 'Zapdos ex MEW 202', to: 'Zapdos exSIR MEW 202' },
  { from: 'Erika\'s Invitation MEW 203', to: 'Erika\'s InvitationSIR MEW 203' },
  { from: 'Giovanni\'s Charisma MEW 204', to: 'Giovanni\'s CharismaSIR MEW 204' },
  { from: 'Mew ex MEW 205', to: 'Mew exHR MEW 205' },
  { from: 'Switch MEW 206', to: 'SwitchHR MEW 206' },
  { from: 'Psychic Energy MEW 207', to: 'Psychic Energy MEW 207' },

  //PAR
  { from: 'Toedscool PAL 57 ', to: 'Toedscool PAL2 57' },
  { from: 'Gimmighoul PAR 88', to: 'Gimmighoul2 PAR 88' },
  //PAR FA
  { from: 'Toedscruel PAR 185', to: 'ToedscruelIR PAR 185' },
  { from: 'Iron Moth PAR 187', to: 'IronMothIR PAR 187' },
  { from: 'Snorunt PAR 188', to: 'SnoruntIR PAR 188' },
  { from: 'Vanillish PAR 190', to: 'VanillishIR PAR 190' },
  { from: 'Blitzle PAR 195', to: 'BlitzleIR PAR 195' },
  { from: 'Joltik PAR 196', to: 'JoltikIR PAR 196' },
  { from: 'Gimmighoul PAR 198', to: 'GimmighoulIR PAR 198' },
  { from: 'Groudon PAR 199', to: 'GroudonIR PAR 199' },
  { from: 'Minior PAR 201', to: 'MiniorIR PAR 201' },
  { from: 'Garganacl PAR 202', to: 'GarganacIR PAR 202' },
  { from: 'Slither Wing PAR 203', to: 'SlitherWingIR PAR 203' },
  { from: 'Garbodor PAR 204', to: 'GarbodorIR PAR 204' },
  { from: 'Yveltal PAR 205', to: 'YveltalIR PAR 205' },
  { from: 'Morpeko PAR 206', to: 'MorpekoIR PAR 206' },
  { from: 'Brute Bonnet PAR 207', to: 'BruteBonnetIR PAR 207' },
  { from: 'Ferrothorn PAR 209', to: 'FerrothorIR PAR 209' },
  { from: 'Aegislash PAR 210', to: 'AegislashIR PAR 210' },
  { from: 'Swablu PAR 213', to: 'SwabluIR PAR 213' },
  { from: 'Porygon-Z PAR 214', to: 'PorygonZIR PAR 214' },
  { from: 'Cyclizar PAR 215', to: 'CyclizarIR PAR 215' },
  { from: 'Iron Jugulis PAR 216', to: 'IronJugulisIR PAR 216' },

  //TEF
  //TEF FA
  { from: 'Grotle TEF 164', to: 'GrotleIR TEF 164' },
  { from: 'Charjabug TEF 169', to: 'CharjabugIR TEF 169' },
  { from: 'Reuniclus TEF 171', to: 'ReuniclusIR TEF 171' },
  { from: 'Gastly TEF 177', to: 'GastlyIR TEF 177' },
  { from: 'Metagross TEF 178', to: 'MetagrossIR TEF 178' },
  { from: 'Chatot TEF 181', to: 'ChatotIR TEF 181' },
  { from: 'Minccino TEF 182', to: 'MinccinoIR TEF 182' },
  { from: 'Cinccino TEF 183', to: 'CinccinoIR TEF 183' },
  { from: 'Torterra ex TEF 185', to: 'TorterraexFA TEF 185' },
  { from: 'Iron Leaves ex TEF 186', to: 'IronLeavesexFA TEF 186' },
  { from: 'Gouging Fire ex TEF 188', to: 'GougingFireexFA TEF 188' },
  { from: 'Walking Wake ex TEF 189', to: 'WalkingWakeexFA TEF 189' },
  { from: 'Iron Crown ex TEF 191', to: 'IronCrownexFA TEF 191' },
  { from: 'Gengar ex TEF 193', to: 'GengarexFA TEF 193' },
  { from: 'Raging Bolt ex TEF 196', to: 'RagingBoltexFA TEF 196' },
  { from: 'Bianca\'s Devotion TEF 197', to: 'BiancasDevotionFA TEF 197' },
  { from: 'Ciphermaniac\'s Codebreaking TEF 198', to: 'CiphermaniacsCodebreakingFA TEF 198' },
  { from: 'Eri TEF 199', to: 'EriFA TEF 199' },
  { from: 'Explorer\'s Guidance TEF 200', to: 'ExplorersGuidanceFA TEF 200' },
  { from: 'Morty\'s Conviction TEF 201', to: 'MortysConvictionFA TEF 201' },
  { from: 'Salvatore TEF 202', to: 'SalvatoreFA TEF 202' },
  { from: 'Iron Leaves ex TEF 203', to: 'IronLeavesexSIR TEF 203' },
  { from: 'Gouging Fire ex TEF 204', to: 'GougingFireexSIR TEF 204' },
  { from: 'Walking Wake ex TEF 205', to: 'WalkingWakeexSIR TEF 205' },
  { from: 'Iron Crown ex TEF 206', to: 'IronCrownexSIR TEF 206' },
  { from: 'Raging Bolt ex TEF 208', to: 'RagingBoltexSIR TEF 208' },
  { from: 'Bianca\'s Devotion TEF 209', to: 'BiancasDevotionSIR TEF 209' },
  { from: 'Eri TEF 210', to: 'EriSIR TEF 210' },
  { from: 'Morty\'s Conviction TEF 211', to: 'MortysConvictionSIR TEF 211' },
  { from: 'Salvatore TEF 212', to: 'SalvatoreSIR TEF 212' },
  { from: 'Iron Leaves ex TEF 213', to: 'IronLeavesexHR TEF 213' },
  { from: 'Gouging Fire ex TEF 214', to: 'GougingFireexHR TEF 214' },
  { from: 'Walking Wake ex TEF 215', to: 'WalkingWakeexHR TEF 215' },
  { from: 'Iron Crown ex TEF 216', to: 'IronCrownexHR TEF 216' },
  { from: 'Raging Bolt ex TEF 218', to: 'RagingBoltexHR TEF 218' },

  //TWM
  { from: 'Applin TWM 17', to: 'Applin TWM 17 17' },
  { from: 'Applin TWM 126', to: 'Applin TWM 126 126' },
  { from: 'Scovillain ex TEF 22', to: 'Scovillain ex PAF 107' },

  //SFA
  { from: 'Bloodmoon Ursaluna SFA 25', to: 'Bloodmoon Ursaluna SV6a 25' },
  { from: 'Janine\'s Secret Art SFA 59', to: 'Janine\'s Secret Technique SFA 59' },

  //SCR
  { from: 'Archaludon SCR 107', to: 'Archaludon SV6a 107' },
  { from: 'Area Zero Underdepths SCR 131', to: 'Area Zero Underdepths SV6a 131' },
  { from: 'Bouffalant SCR 119', to: 'Bouffalant SV7 119' },
  { from: 'Briar SCR 132', to: 'Briar SV7 132' },
  { from: 'Charjabug SCR 52', to: 'Charjabug SV7 52' },
  { from: 'Chewtle SCR 43', to: 'Chewtle SV7 43' },
  { from: 'Cinderace ex SCR 28', to: 'Cinderace ex SV7 28' },
  { from: 'Comfey SCR 63', to: 'Comfey SV7 63' },
  { from: 'Crispin SCR 133', to: 'Crispin SV7 133' },
  { from: 'Drednaw SCR 44', to: 'Drednaw SV7 44' },
  { from: 'Drifblim SCR 61', to: 'Drifblim SV7 61' },
  { from: 'Fan Rotom SCR 118', to: 'Fan Rotom SV7 118' },
  { from: 'Galvantula ex SCR 51', to: 'Galvantula ex SV7 51' },
  { from: 'Glass Trumpet SCR 135', to: 'Glass Trumpet SV7 135' },
  { from: 'Sparkling Crystal SCR 142', to: 'Glistening Crystal SV7 142' },
  { from: 'Grand Tree SCR 136', to: 'Great Tree SV7 136' },
  { from: 'Hoothoot SCR 114', to: 'Hoothoot SV7 114' },
  { from: 'Hydrapple ex SCR 14', to: 'Hydrapple ex SV7 14' },
  { from: 'Joltik SCR 50', to: 'Joltik SV7 50' },
  { from: 'Lapras ex SCR 32', to: 'Lapras ex SV7 32' },
  { from: 'Medicham ex SCR 80', to: 'Medicham ex SV7 80' },
  { from: 'Meditite SCR 77', to: 'Meditite SV7 77' },
  { from: 'Noctowl SCR 115', to: 'Noctowl SV7 115' },
  { from: 'Orthworm ex SCR 110', to: 'Orthworm ex SV7 110' },
  { from: 'Raboot SCR 27', to: 'Raboot SV7 27' },
  { from: 'Scorbunny SCR 26', to: 'Scorbunny SV7 26' },
  { from: 'Terapagos ex SCR 128', to: 'Terapagos ex SV7 128' },
  { from: 'Zeraora SCR 55', to: 'Zeraora SV7 55' },

  //SSP
  { from: 'Eevee SSP 143', to: 'Eevee SVP 143' },
  { from: 'Precious Trolley SSP 185', to: 'Cherish Carrier svLN 185' },
  { from: 'Dragon Elixir SSP 172', to: 'Dragon\'s Elixir SV7a 172' },
  { from: 'Lively Stadium SSP 180', to: 'Exciting Stadium SV8 180' },
  { from: 'Call Bell SSP 165', to: 'Helper Bell SV7a 165' },
  { from: 'Miracle Headset SSP 183', to: 'Miraculous Intercom SV8' },
  { from: 'Brilliant Blender SSP 164', to: 'Perfect Mixer svLS 164' },
  { from: 'Enriching Energy SSP 191', to: 'Rich Energy SV7a 191' },
  { from: 'Alolan Exeggutor ex SSP 133', to: 'Alolan Exeggutor ex SV7a 133' },
  { from: 'Altaria SSP 134', to: 'Altaria SV7a 134' },
  { from: 'Archaludon ex SSP 130', to: 'Archaludon ex SV8 130' },
  { from: 'Azelf SSP 80', to: 'Azelf SV8 80' },
  { from: 'Azumarill SSP 74', to: 'Azumarill svLN 74' },
  { from: 'Black Kyurem SSP 48', to: 'Black Kyurem SV7a 48' },
  { from: 'Ceruledge SSP 35', to: 'Ceruledge SV8 35' },
  { from: 'Ceruledge ex SSP 36', to: 'Ceruledge ex SVP 36' },
  { from: 'Charcadet SSP 32', to: 'Charcadet SVP 32' },
  { from: 'Chien-Pao SSP 56', to: 'Chien-Pao SV8 56' },
  { from: 'Crocalor SSP 30', to: 'Crocalor SV8 30' },
  { from: 'Cyrano SSP 170', to: 'Cyrano SV8 170' },
  { from: 'Deino SSP 117', to: 'Deino SV8 117' },
  { from: 'Dialga SSP 135', to: 'Dialga SV7a 135' },
  { from: 'Drayton SSP 174', to: 'Drayton SV7a 174' },
  { from: 'Duraludon SSP 129', to: 'Duraludon SV7a 129' },
  { from: 'Eternatus SSP 141', to: 'Eternatus SV8 141' },
  { from: 'Exeggcute SSP 1', to: 'Exeggcute SV7a 1' },
  { from: 'Flygon ex SSP 106', to: 'Flygon ex SV7a 106' },
  { from: 'Fuecoco SSP 29', to: 'Fuecoco SV8 29' },
  { from: 'Gouging Fire SSP 38', to: 'Gouging Fire SV7a 38' },
  { from: 'Ho-Oh SSP 19', to: 'Ho-Oh svLS 19' },
  { from: 'Hydreigon ex SSP 119', to: 'Hydreigon ex SV8 119' },
  { from: 'Klefki SSP 128', to: 'Klefki SV7a 128' },
  { from: 'Latias ex SSP 76', to: 'Latias ex SV7a 76' },
  { from: 'Lisia\'s Appeal SSP 179', to: 'Lisia\'s Appeal SV8 179' },
  { from: 'Magnemite SSP 58', to: 'Magnemite SV8 58' },
  { from: 'Marill SSP 73', to: 'Marill svLN 73' },
  { from: 'Mesprit SSP 79', to: 'Mesprit SV8 79' },
  { from: 'Milotic ex SSP 42', to: 'Milotic ex SV8 42' },
  { from: 'Ninetales SSP 17', to: 'Ninetales SV8 17' },
  { from: 'Palkia SSP 136', to: 'Palkia SV7a 136' },
  { from: 'Pikachu ex SSP 57', to: 'Pikachu ex SV8 57' },
  { from: 'Skeledirge SSP 31', to: 'Skeledirge SV8 31' },
  { from: 'Smoochum SSP 75', to: 'Smoochum SV7a 75' },
  { from: 'Sylveon ex SSP 86', to: 'Sylveon ex SVP 86' },
  { from: 'Tatsugiri ex SSP 142', to: 'Tatsugiri ex SV8 142' },
  { from: 'Tera Orb SSP 189', to: 'Tera Orb svLN 189' },
  { from: 'Terapagos SSP 161', to: 'Terapagos SV8 161' },
  { from: 'Togekiss SSP 72', to: 'Togekiss SV8 72' },
  { from: 'Togetic SSP 71', to: 'Togetic SV8 71' },
  { from: 'Togepi SSP 70', to: 'Togepi SV8 70' },
  { from: 'Trapinch SSP 104', to: 'Trapinch SV7a 104' },
  { from: 'Uxie SSP 78', to: 'Uxie SV8 78' },
  { from: 'Vibrava SSP 105', to: 'Vibrava LOR 105' },
  { from: 'Vivillion SSP 7', to: 'Vivillion SV8 7' },
  { from: 'Vulpix SSP 16', to: 'Vulpix SVLS 16' },
  { from: 'Zweilous SSP 118', to: 'Zweilous SV8 118' },
  //SSP FA
  { from: 'Larvesta SSP 196', to: 'LarvestaIR SSP 196' },
];

export const exportReplacements = [
  //Energy
  { from: 'Grass Energy 1', to: 'Grass Energy SVE 1' },
  { from: 'Fire Energy 2', to: 'Fire Energy SVE 2' },
  { from: 'Water Energy 3', to: 'Water Energy SVE 3' },
  { from: 'Lightning Energy 4', to: 'Lightning Energy SVE 4' },
  { from: 'Psychic Energy 5', to: 'Psychic Energy SVE 5' },
  { from: 'Fighting Energy 6', to: 'Fighting Energy SVE 6' },
  { from: 'Darkness Energy 7', to: 'Darkness Energy SVE 7' },
  { from: 'Metal Energy 8', to: 'Metal Energy SVE 8' },

  //BS
  { from: 'Pokémon Breeder BS 76', to: 'Pokemon Breeder BS 76' },
  { from: 'Pokémon Trader BS 77', to: 'Pokemon Trader BS 77' },

  //FO
  { from: 'Gambler FO 61', to: 'Recycle FO 61' },

  //BWP
  { from: 'Tropical Beach BWP50 BWP 50', to: 'Tropical Beach BWP 50' },

  //BLW
  { from: 'Zoroark BL 71', to: 'Zoroark BLW 71' },

  //ROS
  { from: 'Double Dragon Energy SUM 97', to: 'Double Dragon Energy ROS 97' },

  //BKP
  { from: 'Delinquent BKT 98', to: 'Delinquent BKP 98' },

  //GRI
  { from: 'Mallow TEF 127', to: 'Mallow GRI 127' },

  //SHF
  { from: 'Applin SHF SV33', to: 'SnomSV SHF SV33' },

  //DRM
  { from: 'Feebas BCR 28', to: 'Feebas DRM 28' },

  //SLG
  { from: 'Warp Energy SHL 70', to: 'Warp Energy SLG 70' },

  //UPR
  { from: 'Mt. Coronet RCL 130', to: 'Mt. Coronet UPR 130' },

  //UNB
  { from: 'Porygon-Z PAL 157', to: 'Porygon-Z UNB 157' },


  //RCL
  { from: 'Horror Psychic Energy DAA 172', to: 'Horror Psychic Energy RCL 172' },

  //CRE
  { from: 'Klara CRE 145 145', to: 'Klara CRE 145' },

  //PGO
  { from: 'PokeStop PGO 68', to: 'PokéStop PGO 68' },

  //ASR
  { from: 'Hisuian Qwilfish2 ASR 89', to: 'Hisuian Qwilfish ASR 89' },

  //CRZ
  { from: 'Zacian VSTAR 96', to: 'Zacian VSTAR CRZ 96' },

  //SVI
  { from: 'Pokegear SVI 186', to: 'Pokégear 3.0 SVI 186' },
  { from: 'Pokemon Catcher SVI 187', to: 'Pokémon Catcher SVI 187' },
  { from: 'Professor\'s Research SVI 189 189', to: 'Professor\'s Research SVI 189' },
  { from: 'Professor\'s Research SVI 190 189', to: 'Professor\'s Research SVI 190 190' },
  { from: 'Riolu2 SVI 113', to: 'Riolu SVI 113' },

  //SVI FA
  { from: 'ArmarougeIR SVI 203', to: 'Armarouge SVI 203' },
  { from: 'ArvenFA SVI 235', to: 'Arven SVI 235' },
  { from: 'ArvenSIR SVI 249', to: 'Arven SVI 249' },
  { from: 'Fighting EnergyHR SVI 258', to: 'Fighting Energy SVI 258' },
  { from: 'Lightning EnergyHR SVI 257', to: 'Lightning Energy SVI 257' },
  { from: 'Gardevoir exFA SVI 228', to: 'Gardevoir ex SVI 228' },
  { from: 'Gardevoir exSIR SVI 245', to: 'Gardevoir ex SVI 245' },
  { from: 'JacqFA SVI 236', to: 'Jacq SVI 236' },
  { from: 'JacqSIR SVI 250', to: 'Jacq SVI 250' },
  { from: 'KatyFA SVI 237', to: 'Katy SVI 237' },
  { from: 'Koraidon exFA SVI 231', to: 'Koraidon ex SVI 231' },
  { from: 'Koraidon exSIR SVI 247', to: 'Koraidon ex SVI 247' },
  { from: 'Koraidon exHR SVI 254', to: 'Koraidon ex SVI 254' },
  { from: 'Magnezone exFA SVI 226', to: 'Magnezone ex SVI 226' },
  { from: 'Miraidon exFA SVI 227', to: 'Miraidon ex SVI 227' },
  { from: 'Miraidon exSIR SVI 244', to: 'Miraidon ex SVI 244' },
  { from: 'Miraidon exHR SVI 253', to: 'Miraidon ex SVI 253' },
  { from: 'MiriamFA SVI 238', to: 'Miriam SVI 238' },
  { from: 'MiriamSIR SVI 251', to: 'Miriam SVI 251' },
  { from: 'Nest BallHR SVI 255', to: 'Nest Ball SVI 255' },
  { from: 'PennyFA SVI 239', to: 'Penny SVI 239' },
  { from: 'PennySIR SVI 252', to: 'Penny SVI 252' },
  { from: "Professor's ResearchFA1 SVI 242", to: "Professor's Research SVI 242" },
  { from: "Professor's ResearchFA2 SVI 241", to: "Professor's Research SVI 241" },
  { from: 'RaltsIR SVI 211', to: 'Ralts SVI 211' },
  { from: 'Rare CandyHR SVI 256', to: 'Rare Candy SVI 256' },
  { from: 'SkwovetIR SVI 222', to: 'Skwovet SVI 222' },
  { from: 'Team Star GruntFA SVI 242', to: 'Team Star Grunt SVI 242' },

  //PAL
  { from: 'Frigibax PAL1 57 ', to: 'Frigibax PAL 57' },
  { from: 'Frigibax PAL2 58 ', to: 'Frigibax PAL 58' },
  //PAL FA
  { from: 'FrigibaxIR PAL 208', to: 'Frigibax PAL 208' },
  { from: 'ArctibaxIR PAL 209', to: 'Arctibax PAL 209' },
  { from: 'BaxcaliburIR PAL 210', to: 'Baxcalibur PAL 210' },
  { from: 'FlamigoIR PAL 227', to: 'Flamigo PAL 227' },
  { from: 'Meowscarada exFA PAL 231', to: 'Meowscarada ex PAL 231' },
  { from: 'Wo-Chien exFA PAL 232', to: 'Wo-Chien ex PAL 232' },
  { from: 'Chi-Yu exFA PAL 234', to: 'Chi-Yu ex PAL 234' },
  { from: 'Chien-Pao exFA PAL 236', to: 'Chien-Pao ex PAL 236' },
  { from: 'Ting-Lu exFA PAL 243', to: 'Ting-Lu ex PAL 243' },
  { from: 'Noivern exFA PAL 246', to: 'Noivern ex PAL 246' },
  { from: 'Squawkabilly exFA PAL 247', to: 'Squawkabilly ex PAL 247' },
  { from: 'Boss\'s OrdersFA PAL 248', to: 'Boss\'s Orders PAL 248' },
  { from: 'ClavellFA PAL 249', to: 'Clavell PAL 249' },
  { from: 'GiacomoFA PAL 252', to: 'Giacomo PAL 252' },
  { from: 'GrushaFA PAL 253', to: 'Grusha PAL 253' },
  { from: 'IonoFA PAL 254', to: 'Iono PAL 254' },
  { from: 'Meowscarada exSIR PAL 256', to: 'Meowscarada ex PAL 256' },
  { from: 'Wo-Chien exSIR PAL 257', to: 'Wo-Chien ex PAL 257' },
  { from: 'Chi-Yu exSIR PAL 259', to: 'Chi-Yu ex PAL 259' },
  { from: 'Chien-Pao exSIR PAL 261', to: 'Chien-Pao ex PAL 261' },
  { from: 'Ting-Lu exSIR PAL 263', to: 'Ting-Lu ex PAL 263' },
  { from: 'Squawkabilly exSIR PAL 264', to: 'Squawkabilly ex PAL 264' },
  { from: 'Boss\'s OrdersSIR PAL 265', to: 'Boss\'s Orders PAL 265' },
  { from: 'GiacomoSIR PAL 267', to: 'Giacomo PAL 267' },
  { from: 'GrushaSIR PAL 268', to: 'Grusha PAL 268' },
  { from: 'IonoSIR PAL 269', to: 'Iono PAL 269' },
  { from: 'Meowscarada exHR PAL 271', to: 'Meowscarada ex PAL 271' },
  { from: 'Chien-Pao exHR PAL 274', to: 'Chien-Pao ex PAL 274' },
  { from: 'Ting-Lu exHR PAL 275', to: 'Ting-Lu ex PAL 275' },
  { from: 'Super RodHR PAL 276', to: 'Super Rod PAL 276' },
  { from: 'Superior Energy RetrievalHR PAL 277', to: 'Superior Energy Retrieval PAL 277' },

  //151
  //151 FA
  { from: 'BulbasaurIR MEW 166', to: 'Bulbasaur MEW 166' },
  { from: 'IvysaurIR MEW 167', to: 'Ivysaur MEW 167' },
  { from: 'CharmanderIR MEW 168', to: 'Charmander MEW 168' },
  { from: 'CharmeleonIR MEW 169', to: 'Charmeleon MEW 169' },
  { from: 'SquirtleIR MEW 170', to: 'Squirtle MEW 170' },
  { from: 'WartortleIR MEW 171', to: 'Wartortle MEW 171' },
  { from: 'NidokingIR MEW 174', to: 'Nidoking MEW 174' },
  { from: 'Venusaur exFA MEW 182', to: 'Venusaur ex MEW 182' },
  { from: 'Charizard exFA MEW 183', to: 'Charizard ex MEW 183' },
  { from: 'Blastoise exFA MEW 184', to: 'Blastoise ex MEW 184' },
  { from: 'Arbok exFA MEW 185', to: 'Arbok ex MEW 185' },
  { from: 'Alakazam exFA MEW 188', to: 'Alakazam ex MEW 188' },
  { from: 'Kangaskhan exFA MEW 190', to: 'Kangaskhan ex MEW 190' },
  { from: 'Zapdos exFA MEW 192', to: 'Zapdos ex MEW 192' },
  { from: 'Mew exFA MEW 193', to: 'Mew ex MEW 193' },
  { from: 'Erika\'s InvitationFA MEW 196', to: 'Erika\'s Invitation MEW 196' },
  { from: 'Giovanni\'s CharismaFA MEW 197', to: 'Giovanni\'s Charisma MEW 197' },
  { from: 'Venusaur exSIR MEW 198', to: 'Venusaur ex MEW 198' },
  { from: 'Charizard exSIR MEW 199', to: 'Charizard ex MEW 199' },
  { from: 'Blastoise exSIR MEW 200', to: 'Blastoise ex MEW 200' },
  { from: 'Alakazam exSIR MEW 201', to: 'Alakazam ex MEW 201' },
  { from: 'Zapdos exSIR MEW 202', to: 'Zapdos ex MEW 202' },
  { from: 'Erika\'s InvitationSIR MEW 203', to: 'Erika\'s Invitation MEW 203' },
  { from: 'Giovanni\'s CharismaSIR MEW 204', to: 'Giovanni\'s Charisma MEW 204' },
  { from: 'Mew exHR MEW 205', to: 'Mew ex MEW 205' },
  { from: 'SwitchHR MEW 206', to: 'Switch MEW 206' },
  { from: 'Psychic Energy MEW 207', to: 'Psychic Energy MEW 207' },

  //PAR
  { from: 'Toedscool PAL2 57 ', to: 'Toedscool PAL 57' },
  { from: 'Gimmighoul2 PAR 88', to: 'Gimmighoul PAR 88' },
  //PAR FA
  { from: 'ToedscruelIR PAR 185', to: 'Toedscruel PAR 185' },
  { from: 'IronMothIR PAR 187', to: 'Iron Moth PAR 187' },
  { from: 'SnoruntIR PAR 188', to: 'Snorunt PAR 188' },
  { from: 'VanillishIR PAR 190', to: 'Vanillish PAR 190' },
  { from: 'BlitzleIR PAR 195', to: 'Blitzle PAR 195' },
  { from: 'JoltikIR PAR 196', to: 'Joltik PAR 196' },
  { from: 'GimmighoulIR PAR 198', to: 'Gimmighoul PAR 198' },
  { from: 'GroudonIR PAR 199', to: 'Groudon PAR 199' },
  { from: 'MiniorIR PAR 201', to: 'Minior PAR 201' },
  { from: 'GarganacIR PAR 202', to: 'Garganacl PAR 202' },
  { from: 'SlitherWingIR PAR 203', to: 'Slither Wing PAR 203' },
  { from: 'GarbodorIR PAR 204', to: 'Garbodor PAR 204' },
  { from: 'YveltalIR PAR 205', to: 'Yveltal PAR 205' },
  { from: 'MorpekoIR PAR 206', to: 'Morpeko PAR 206' },
  { from: 'BruteBonnetIR PAR 207', to: 'Brute Bonnet PAR 207' },
  { from: 'FerrothorIR PAR 209', to: 'Ferrothorn PAR 209' },
  { from: 'AegislashIR PAR 210', to: 'Aegislash PAR 210' },
  { from: 'SwabluIR PAR 213', to: 'Swablu PAR 213' },
  { from: 'PorygonZIR PAR 214', to: 'Porygon-Z PAR 214' },
  { from: 'CyclizarIR PAR 215', to: 'Cyclizar PAR 215' },
  { from: 'IronJugulisIR PAR 216', to: 'Iron Jugulis PAR 216' },
  { from: 'FroslassexFA PAR 217', to: 'Froslass ex PAR 217' },
  { from: 'GarchompexFA PAR 219', to: 'Garchomp ex PAR 219' },
  { from: 'TsareenaexFA PAR 220', to: 'Tsareena ex PAR 220' },
  { from: 'TapuKokoexFA PAR 222', to: 'Tapu Koko ex PAR 222' },
  { from: 'IronHandsexFA PAR 223', to: 'Iron Hands ex PAR 223' },
  { from: 'IronValiantexFA PAR 225', to: 'Iron Valiant ex PAR 225' },
  { from: 'HoopaexFA PAR 226', to: 'Hoopa ex PAR 226' },
  { from: 'SandyShocksexFA PAR 228', to: 'Sandy Shocks ex PAR 228' },
  { from: 'RoaringMoonexFA PAR 229', to: 'Roaring Moon ex PAR 229' },
  { from: 'GholdengoexFA PAR 231', to: 'Gholdengo ex PAR 231' },
  { from: 'BombirdierexFA PAR 234', to: 'Bombirdier ex PAR 234' },
  { from: 'MelaFA PAR 236', to: 'Mela PAR 236' },
  { from: 'ProfessorSadasVitalityFA PAR 239', to: 'Professor Sada\'s Vitality PAR 239' },
  { from: 'ProfessorTurosScenarioFA PAR 240', to: 'Professor Turo\'s Scenario PAR 240' },
  { from: 'TulipFA PAR 244', to: 'Tulip PAR 244' },
  { from: 'GarchompexSIR PAR 245', to: 'Garchomp ex PAR 245' },
  { from: 'TapuKokoexSIR PAR 247', to: 'Tapu Koko ex PAR 247' },
  { from: 'IronHandsexSIR PAR 248', to: 'Iron Hands ex PAR 248' },
  { from: 'IronValiantexSIR PAR 249', to: 'Iron Valiant ex PAR 249' },
  { from: 'SandyShocksexSIR PAR 250', to: 'Sandy Shocks ex PAR 250' },
  { from: 'RoaringMoonexSIR PAR 251', to: 'Roaring Moon ex PAR 251' },
  { from: 'GholdengoexSIR PAR 252', to: 'Gholdengo ex PAR 252' },
  { from: 'MelaSIR PAR 254', to: 'Mela PAR 254' },
  { from: 'ProfessorSadasVitalitySIR PAR 256', to: 'Professor Sada\'s Vitality PAR 256' },
  { from: 'ProfessorTurosScenarioSIR PAR 257', to: 'Professor Turo\'s Scenario PAR 257' },
  { from: 'TulipSIR PAR 259', to: 'Tulip PAR 259' },
  { from: 'GarchompexHR PAR 260', to: 'Garchomp ex PAR 260' },
  { from: 'IronValiantexHR PAR 261', to: 'Iron Valiant ex PAR 261' },
  { from: 'RoaringMoonexHR PAR 262', to: 'Roaring Moon ex PAR 262' },
  { from: 'BeachCourtHR PAR 263', to: 'Beach Court PAR 263' },
  { from: 'CounterCatcherHR PAR 264', to: 'Counter Catcher PAR 264' },
  { from: 'LuxuriousCapeHR PAR 265', to: 'Luxurious Cape PAR 265' },
  { from: 'ReversalEnergyHR PAR 266', to: 'Reversal Energy PAR 266' },

  //TEF
  //TEF FA
  { from: 'GrotleIR TEF 164', to: 'Grotle TEF 164' },
  { from: 'CharjabugIR TEF 169', to: 'Charjabug TEF 169' },
  { from: 'ReuniclusIR TEF 171', to: 'Reuniclus TEF 171' },
  { from: 'GastlyIR TEF 177', to: 'Gastly TEF 177' },
  { from: 'MetagrossIR TEF 178', to: 'Metagross TEF 178' },
  { from: 'ChatotIR TEF 181', to: 'Chatot TEF 181' },
  { from: 'MinccinoIR TEF 182', to: 'Minccino TEF 182' },
  { from: 'CinccinoIR TEF 183', to: 'Cinccino TEF 183' },
  { from: 'TorterraexFA TEF 185', to: 'Torterra ex TEF 185' },
  { from: 'IronLeavesexFA TEF 186', to: 'Iron Leaves ex TEF 186' },
  { from: 'GougingFireexFA TEF 188', to: 'Gouging Fire ex TEF 188' },
  { from: 'WalkingWakeexFA TEF 189', to: 'Walking Wake ex TEF 189' },
  { from: 'IronCrownexFA TEF 191', to: 'Iron Crown ex TEF 191' },
  { from: 'GengarexFA TEF 193', to: 'Gengar ex TEF 193' },
  { from: 'RagingBoltexFA TEF 196', to: 'Raging Bolt ex TEF 196' },
  { from: 'BiancasDevotionFA TEF 197', to: 'Bianca\'s Devotion TEF 197' },
  { from: 'CiphermaniacsCodebreakingFA TEF 198', to: 'Ciphermaniac\'s Codebreaking TEF 198' },
  { from: 'EriFA TEF 199', to: 'Eri TEF 199' },
  { from: 'ExplorersGuidanceFA TEF 200', to: 'Explorer\'s Guidance TEF 200' },
  { from: 'MortysConvictionFA TEF 201', to: 'Morty\'s Conviction TEF 201' },
  { from: 'SalvatoreFA TEF 202', to: 'Salvatore TEF 202' },
  { from: 'IronLeavesexSIR TEF 203', to: 'Iron Leaves ex TEF 203' },
  { from: 'GougingFireexSIR TEF 204', to: 'Gouging Fire ex TEF 204' },
  { from: 'WalkingWakeexSIR TEF 205', to: 'Walking Wake ex TEF 205' },
  { from: 'IronCrownexSIR TEF 206', to: 'Iron Crown ex TEF 206' },
  { from: 'RagingBoltexSIR TEF 208', to: 'Raging Bolt ex TEF 208' },
  { from: 'BiancasDevotionSIR TEF 209', to: 'Bianca\'s Devotion TEF 209' },
  { from: 'EriSIR TEF 210', to: 'Eri TEF 210' },
  { from: 'MortysConvictionSIR TEF 211', to: 'Morty\'s Conviction TEF 211' },
  { from: 'SalvatoreSIR TEF 212', to: 'Salvatore TEF 212' },
  { from: 'IronLeavesexHR TEF 213', to: 'Iron Leaves ex TEF 213' },
  { from: 'GougingFireexHR TEF 214', to: 'Gouging Fire ex TEF 214' },
  { from: 'WalkingWakeexHR TEF 215', to: 'Walking Wake ex TEF 215' },
  { from: 'IronCrownexHR TEF 216', to: 'Iron Crown ex TEF 216' },
  { from: 'RagingBoltexHR TEF 218', to: 'Raging Bolt ex TEF 218' },

  //TWM
  { from: 'Applin TWM 17 17', to: 'Applin TWM 17' },
  { from: 'Applin TWM 126 126', to: 'Applin TWM 126' },
  { from: 'Scovillain ex PAF 107', to: 'Scovillain ex TEF 22' },

  //SFA
  { from: 'Bloodmoon Ursaluna SV6a 25', to: 'Bloodmoon Ursaluna SFA 25' },
  { from: 'Janine\'s Secret Technique SFA 59', to: 'Janine\'s Secret Art SFA 59' },

  //SCR
  { from: 'Archaludon SV6a 107', to: 'Archaludon SCR 107' },
  { from: 'Area Zero Underdepths SV6a 131', to: 'Area Zero Underdepths SCR 131' },
  { from: 'Bouffalant SV7 119', to: 'Bouffalant SCR 119' },
  { from: 'Briar SV7 132', to: 'Briar SCR 132' },
  { from: 'Charjabug SV7 52', to: 'Charjabug SCR 52' },
  { from: 'Chewtle SV7 43', to: 'Chewtle SCR 43' },
  { from: 'Cinderace ex SV7 28', to: 'Cinderace ex SCR 28' },
  { from: 'Comfey SV7 63', to: 'Comfey SCR 63' },
  { from: 'Crispin SV7 133', to: 'Crispin SCR 133' },
  { from: 'Drednaw SV7 44', to: 'Drednaw SCR 44' },
  { from: 'Drifblim SV7 61', to: 'Drifblim SCR 61' },
  { from: 'Fan Rotom SV7 118', to: 'Fan Rotom SCR 118' },
  { from: 'Galvantula ex SV7 51', to: 'Galvantula ex SCR 51' },
  { from: 'Glass Trumpet SV7 135', to: 'Glass Trumpet SCR 135' },
  { from: 'Glistening Crystal SV7 142', to: 'Sparkling Crystal SCR 142' },
  { from: 'Great Tree SV7 136', to: 'Grand Tree SCR 136' },
  { from: 'Hoothoot SV7 114', to: 'Hoothoot SCR 114' },
  { from: 'Hydrapple ex SV7 14', to: 'Hydrapple ex SCR 14' },
  { from: 'Joltik SV7 50', to: 'Joltik SCR 50' },
  { from: 'Lapras ex SV7 32', to: 'Lapras ex SCR 32' },
  { from: 'Medicham ex SV7 80', to: 'Medicham ex SCR 80' },
  { from: 'Meditite SV7 77', to: 'Meditite SCR 77' },
  { from: 'Noctowl SV7 115', to: 'Noctowl SCR 115' },
  { from: 'Orthworm ex SV7 110', to: 'Orthworm ex SCR 110' },
  { from: 'Raboot SV7 27', to: 'Raboot SCR 27' },
  { from: 'Scorbunny SV7 26', to: 'Scorbunny SCR 26' },
  { from: 'Terapagos ex SV7 128', to: 'Terapagos ex SCR 128' },
  { from: 'Zeraora SV7 55', to: 'Zeraora SCR 55' },

  //SSP
  { from: 'Eevee SVP 143', to: 'Eevee SSP 143' },
  { from: 'Cherish Carrier svLN 185', to: 'Precious Trolley SSP 185' },
  { from: 'Dragon\'s Elixir SV7a 172', to: 'Dragon Elixir SSP 172' },
  { from: 'Exciting Stadium SV8 180', to: 'Lively Stadium SSP 180' },
  { from: 'Helper Bell SV8 165', to: 'Call Bell SSP 165' },
  { from: 'Miraculous Intercom SV8 183', to: 'Miracle Headset SSP 183' },
  { from: 'Perfect Mixer svLS 164', to: 'Brilliant Blender SSP 164' },
  { from: 'Rich Energy SV7a 191', to: 'Enriching Energy SSP 191' },
  { from: 'Alolan Exeggutor ex SV7a 133', to: 'Alolan Exeggutor ex SSP 133' },
  { from: 'Altaria SV7a 134', to: 'Altaria SSP 134' },
  { from: 'Archaludon ex SV8 130', to: 'Archaludon ex SSP 130' },
  { from: 'Azelf SV8 80', to: 'Azelf SSP 80' },
  { from: 'Azumarill svLN 74', to: 'Azumarill SSP 74' },
  { from: 'Black Kyurem SV7a 48', to: 'Black Kyurem SSP 48' },
  { from: 'Ceruledge SV8 35', to: 'Ceruledge SSP 35' },
  { from: 'Ceruledge ex SVP 36', to: 'Ceruledge ex SSP 36' },
  { from: 'Charcadet SVP 32', to: 'Charcadet SSP 32' },
  { from: 'Chien-Pao SV8 56', to: 'Chien-Pao SSP 56' },
  { from: 'Crocalor SV8 30', to: 'Crocalor SSP 30' },
  { from: 'Cyrano SV8 170', to: 'Cyrano SSP 170' },
  { from: 'Deino SV8 117', to: 'Deino SSP 117' },
  { from: 'Dialga SV7a 135', to: 'Dialga SSP 135' },
  { from: 'Drayton SV7a 174', to: 'Drayton SSP 174' },
  { from: 'Duraludon SV7a 129', to: 'Duraludon SSP 129' },
  { from: 'Eternatus SV8 141', to: 'Eternatus SSP 141' },
  { from: 'Exeggcute SV7a 1', to: 'Exeggcute SSP 1' },
  { from: 'Flygon ex SV7a 106', to: 'Flygon ex SSP 106' },
  { from: 'Fuecoco SV8 29', to: 'Fuecoco SSP 29' },
  { from: 'Gouging Fire SV7a 38', to: 'Gouging Fire SSP 38' },
  { from: 'Ho-Oh svLS 19', to: 'Ho-Oh SSP 19' },
  { from: 'Hydreigon ex SV8 119', to: 'Hydreigon ex SSP 119' },
  { from: 'Klefki SV7a 128', to: 'Klefki SSP 128' },
  { from: 'Latias ex SV7a 76', to: 'Latias ex SSP 76' },
  { from: 'Lisia\'s Appeal SV8 179', to: 'Lisia\'s Appeal SSP 179' },
  { from: 'Magnemite SV8 58', to: 'Magnemite SSP 58' },
  { from: 'Marill svLN 73', to: 'Marill SSP 73' },
  { from: 'Mesprit SV8 79', to: 'Mesprit SSP 79' },
  { from: 'Milotic ex SV8 42', to: 'Milotic ex SSP 42' },
  { from: 'Ninetales SV8 17', to: 'Ninetales SSP 17' },
  { from: 'Palkia SV7a 136', to: 'Palkia SSP 136' },
  { from: 'Pikachu ex SV8 57', to: 'Pikachu ex SSP 57' },
  { from: 'Skeledirge SV8 31', to: 'Skeledirge SSP 31' },
  { from: 'Smoochum SV7a 75', to: 'Smoochum SSP 75' },
  { from: 'Sylveon ex SVP 86', to: 'Sylveon ex SSP 86' },
  { from: 'Tatsugiri ex SV8 142', to: 'Tatsugiri ex SSP 142' },
  { from: 'Tera Orb svLN 189', to: 'Tera Orb SSP 189' },
  { from: 'Terapagos SV8 161', to: 'Terapagos SSP 161' },
  { from: 'Togekiss SV8 72', to: 'Togekiss SSP 72' },
  { from: 'Togetic SV8 71', to: 'Togetic SSP 71' },
  { from: 'Togepi SV8 70', to: 'Togepi SSP 70' },
  { from: 'Trapinch SV7a 104', to: 'Trapinch SSP 104' },
  { from: 'Uxie SV8 78', to: 'Uxie SSP 78' },
  { from: 'Vibrava LOR 105', to: 'Vibrava SSP 105' },
  { from: 'Vivillion SV8 7', to: 'Vivillion SSP 7' },
  { from: 'Vulpix SVLS 16', to: 'Vulpix SSP 16' },
  { from: 'Zweilous SV8 118', to: 'Zweilous SSP 118' },
  //SSP FA
  { from: 'LarvestaIR SSP 196', to: 'Larvesta SSP 196' },
];